"""V2

Revision ID: a692b3322c71
Revises: 
Create Date: 2023-07-19 21:21:41.246039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a692b3322c71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=15), nullable=True),
    sa.Column('body_camera', sa.Boolean(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('race', sa.String(length=15), nullable=True),
    sa.Column('race_source', sa.String(length=20), nullable=True),
    sa.Column('was_mental_illness_related', sa.Boolean(), nullable=True),
    sa.Column('threat_type', sa.String(length=20), nullable=True),
    sa.Column('armed_with', sa.String(length=50), nullable=True),
    sa.Column('flee_status', sa.String(length=10), nullable=True),
    sa.Column('agency_ids', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('db_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_person_db_id'), 'person', ['db_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_person_db_id'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
