"""V2

Revision ID: a7176073311b
Revises: a692b3322c71
Create Date: 2023-07-19 21:34:18.055564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7176073311b'
down_revision = 'a692b3322c71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('county', sa.String(length=50), nullable=True))
    op.drop_column('person', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('person', 'county')
    # ### end Alembic commands ###
