"""Add agency table

Revision ID: e827dcc448ad
Revises: a7176073311b
Create Date: 2023-07-20 10:32:48.569183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e827dcc448ad'
down_revision = 'a7176073311b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.Column('oricodes', sa.String(length=50), nullable=True),
    sa.Column('total_shootings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('db_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_agency_db_id'), 'agency', ['db_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agency_db_id'), table_name='agency')
    op.drop_table('agency')
    # ### end Alembic commands ###
