"""create user and person tables

Revision ID: e9f220e36615
Revises:
Create Date: 2023-06-24 18:48:51.412952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9f220e36615"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("db_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("date", sa.String(length=15), nullable=True),
        sa.Column("manner_of_death", sa.String(length=50), nullable=True),
        sa.Column("armed", sa.String(length=50), nullable=True),
        sa.Column("age", sa.Float(), nullable=True),
        sa.Column("gender", sa.String(length=5), nullable=True),
        sa.Column("race", sa.String(length=5), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("signs_of_mental_illness", sa.Boolean(), nullable=True),
        sa.Column("threat_level", sa.String(length=50), nullable=True),
        sa.Column("flee", sa.String(length=50), nullable=True),
        sa.Column("body_camera", sa.Boolean(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("is_geocoding_exact", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("db_id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_person_db_id"), "person", ["db_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("password", sa.String(length=100), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_person_db_id"), table_name="person")
    op.drop_table("person")
    # ### end Alembic commands ###
